M48
; DRILL file {KiCad (6.0.9-0)} date 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-04T14:35:13+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0374
%
G90
G05
T1
X4.6911Y-3.6598
X4.6911Y-3.8874
T2
X6.6774Y-4.3161
X6.9452Y-4.3161
T0
M30
